workflows:
  ios-workflow:
    name: iOS Build

    environment:
      node: latest
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Expo prebuild (iOS)
        script: |
          npx expo prebuild --platform ios --non-interactive

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS (auto detect scheme)
        script: |
          cd ios
          SCHEME=$(xcodebuild -list | grep -A 1 "Schemes" | tail -n 1 | xargs)
          echo "Using scheme: $SCHEME"

          xcodebuild \
          -workspace *.xcworkspace \
          -scheme "$SCHEME" \
          -configuration Release \
          -archivePath build/App.xcarchive archive

    artifacts:
      - ios/build/**/*.ipa
      - ios/build/**/*.xcarchive
