export const STRINGS = {
  appName: "عالم زمرد",
  tagline: "جمالك في بيتك",

  tabs: {
    home: "الرئيسية",
    categories: "التصنيفات",
    orders: "طلباتي",
    profile: "حسابي",
  },

  auth: {
    welcome: "مرحباً بك",
    welcomeBack: "أهلاً بعودتك",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    phone: "رقم الهاتف",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    name: "الاسم الكامل",
    otp: "رمز التحقق",
    sendOtp: "إرسال الرمز",
    verifyOtp: "تحقق من الرمز",
    otpSent: "تم إرسال رمز التحقق إلى هاتفك",
    forgotPassword: "نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    asCustomer: "كعميل",
    asProvider: "كمزود خدمة",
    selectRole: "اختر نوع الحساب",
    salon: "صالون",
    freelancer: "فريلانسر",
    logout: "تسجيل الخروج",
  },

  home: {
    greeting: "مرحباً",
    searchPlaceholder: "ابحث عن خدمة...",
    nearbyProviders: "مزودو الخدمة القريبون",
    popularServices: "الخدمات الشائعة",
    featuredCategories: "التصنيفات المميزة",
    seeAll: "عرض الكل",
    requestService: "طلب خدمة",
    howFar: "ضمن نطاق",
    km: "كم",
  },

  categories: {
    title: "التصنيفات",
    hair: "الشعر",
    makeup: "المكياج",
    nails: "الأظافر",
    skincare: "العناية بالبشرة",
    eyebrows: "الحواجب",
    eyelashes: "الرموش",
    waxing: "إزالة الشعر",
    henna: "الحناء",
    massage: "المساج",
    other: "أخرى",
  },

  request: {
    title: "طلب خدمة",
    selectService: "اختر الخدمة",
    selectLocation: "حدد موقعك",
    selectTime: "اختر الموعد",
    notes: "ملاحظات إضافية",
    submit: "إرسال الطلب",
    waiting: "في انتظار العروض...",
    offersReceived: "العروض المستلمة",
    noOffers: "لم يتم استلام عروض بعد",
    selectOffer: "اختر هذا العرض",
    confirmRequest: "تأكيد الطلب",
    cancel: "إلغاء الطلب",
    price: "السعر",
    eta: "وقت الوصول",
    minutes: "دقيقة",
  },

  orders: {
    title: "طلباتي",
    active: "النشطة",
    completed: "المكتملة",
    cancelled: "الملغية",
    pending: "في الانتظار",
    accepted: "مقبول",
    inProgress: "جارٍ التنفيذ",
    done: "منتهي",
    rate: "قيّم الخدمة",
    rateNow: "قيّم الآن",
    trackOrder: "تتبع الطلب",
    noOrders: "لا توجد طلبات",
    orderDetails: "تفاصيل الطلب",
  },

  profile: {
    title: "حسابي",
    editProfile: "تعديل الملف الشخصي",
    wallet: "محفظتي",
    myServices: "خدماتي",
    settings: "الإعدادات",
    language: "اللغة",
    notifications: "الإشعارات",
    help: "المساعدة",
    about: "عن التطبيق",
    balance: "الرصيد",
    recharge: "شحن الرصيد",
    history: "سجل المعاملات",
    rating: "تقييمي",
    totalOrders: "إجمالي الطلبات",
    favorites: "المفضلة",
  },

  provider: {
    verification: "التحقق من الهوية",
    portfolio: "معرض الأعمال",
    services: "الخدمات المقدمة",
    addService: "إضافة خدمة",
    editService: "تعديل الخدمة",
    incomingRequests: "الطلبات الواردة",
    makeOffer: "تقديم عرض",
    offerPrice: "سعر العرض",
    arrivalTime: "وقت الوصول",
    submitOffer: "إرسال العرض",
    acceptRequest: "قبول الطلب",
    startService: "بدء الخدمة",
    completeService: "إنهاء الخدمة",
    earnings: "الأرباح",
    commission: "العمولة",
  },

  common: {
    save: "حفظ",
    cancel: "إلغاء",
    confirm: "تأكيد",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    back: "رجوع",
    next: "التالي",
    done: "تم",
    loading: "جارٍ التحميل...",
    error: "حدث خطأ",
    tryAgain: "حاول مرة أخرى",
    noData: "لا توجد بيانات",
    success: "تمت العملية بنجاح",
    currency: "دينار",
    sar: "د.أ",
    required: "هذا الحقل مطلوب",
    optional: "اختياري",
    search: "بحث",
    filter: "تصفية",
    sort: "ترتيب",
    share: "مشاركة",
    copy: "نسخ",
    close: "إغلاق",
    refresh: "تحديث",
    all: "الكل",
  },

  rating: {
    title: "قيّم الخدمة",
    howWas: "كيف كانت تجربتك؟",
    addComment: "أضف تعليقاً (اختياري)",
    submit: "إرسال التقييم",
    excellent: "ممتاز",
    good: "جيد",
    average: "متوسط",
    poor: "ضعيف",
    terrible: "سيء جداً",
  },
};
